/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfOdds;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfOddsRecord extends UpdatableRecordImpl<VfOddsRecord> implements Record4<Integer, Integer, String, BigDecimal> {

    private static final long serialVersionUID = -1084529422;

    /**
     * Setter for <code>VF.vf_odds.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_odds.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_odds.match_id</code>.
     */
    public void setMatchId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_odds.match_id</code>.
     */
    public Integer getMatchId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VF.vf_odds.odd_type</code>.
     */
    public void setOddType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_odds.odd_type</code>.
     */
    public String getOddType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>VF.vf_odds.odd_value</code>.
     */
    public void setOddValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_odds.odd_value</code>.
     */
    public BigDecimal getOddValue() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, String, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, String, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfOdds.VF_ODDS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return VfOdds.VF_ODDS.MATCH_ID;
    }

    @Override
    public Field<String> field3() {
        return VfOdds.VF_ODDS.ODD_TYPE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return VfOdds.VF_ODDS.ODD_VALUE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMatchId();
    }

    @Override
    public String component3() {
        return getOddType();
    }

    @Override
    public BigDecimal component4() {
        return getOddValue();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMatchId();
    }

    @Override
    public String value3() {
        return getOddType();
    }

    @Override
    public BigDecimal value4() {
        return getOddValue();
    }

    @Override
    public VfOddsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VfOddsRecord value2(Integer value) {
        setMatchId(value);
        return this;
    }

    @Override
    public VfOddsRecord value3(String value) {
        setOddType(value);
        return this;
    }

    @Override
    public VfOddsRecord value4(BigDecimal value) {
        setOddValue(value);
        return this;
    }

    @Override
    public VfOddsRecord values(Integer value1, Integer value2, String value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfOddsRecord
     */
    public VfOddsRecord() {
        super(VfOdds.VF_ODDS);
    }

    /**
     * Create a detached, initialised VfOddsRecord
     */
    public VfOddsRecord(Integer id, Integer matchId, String oddType, BigDecimal oddValue) {
        super(VfOdds.VF_ODDS);

        set(0, id);
        set(1, matchId);
        set(2, oddType);
        set(3, oddValue);
    }
}
