/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfSport;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfSportRecord extends UpdatableRecordImpl<VfSportRecord> implements Record4<String, String, Integer, Integer> {

    private static final long serialVersionUID = 1017267595;

    /**
     * Setter for <code>VF.vf_sport.code</code>.
     */
    public void setCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_sport.code</code>.
     */
    public String getCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>VF.vf_sport.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_sport.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VF.vf_sport.halftime_duration</code>.
     */
    public void setHalftimeDuration(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_sport.halftime_duration</code>.
     */
    public Integer getHalftimeDuration() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VF.vf_sport.period_duration</code>.
     */
    public void setPeriodDuration(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_sport.period_duration</code>.
     */
    public Integer getPeriodDuration() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return VfSport.VF_SPORT.CODE;
    }

    @Override
    public Field<String> field2() {
        return VfSport.VF_SPORT.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return VfSport.VF_SPORT.HALFTIME_DURATION;
    }

    @Override
    public Field<Integer> field4() {
        return VfSport.VF_SPORT.PERIOD_DURATION;
    }

    @Override
    public String component1() {
        return getCode();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getHalftimeDuration();
    }

    @Override
    public Integer component4() {
        return getPeriodDuration();
    }

    @Override
    public String value1() {
        return getCode();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getHalftimeDuration();
    }

    @Override
    public Integer value4() {
        return getPeriodDuration();
    }

    @Override
    public VfSportRecord value1(String value) {
        setCode(value);
        return this;
    }

    @Override
    public VfSportRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public VfSportRecord value3(Integer value) {
        setHalftimeDuration(value);
        return this;
    }

    @Override
    public VfSportRecord value4(Integer value) {
        setPeriodDuration(value);
        return this;
    }

    @Override
    public VfSportRecord values(String value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfSportRecord
     */
    public VfSportRecord() {
        super(VfSport.VF_SPORT);
    }

    /**
     * Create a detached, initialised VfSportRecord
     */
    public VfSportRecord(String code, String name, Integer halftimeDuration, Integer periodDuration) {
        super(VfSport.VF_SPORT);

        set(0, code);
        set(1, name);
        set(2, halftimeDuration);
        set(3, periodDuration);
    }
}
