/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfLeague implements Serializable {

    private static final long serialVersionUID = 250742072;

    private Integer id;
    private String  name;
    private String  sport;

    public VfLeague() {}

    public VfLeague(VfLeague value) {
        this.id = value.id;
        this.name = value.name;
        this.sport = value.sport;
    }

    public VfLeague(
        Integer id,
        String  name,
        String  sport
    ) {
        this.id = id;
        this.name = name;
        this.sport = sport;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSport() {
        return this.sport;
    }

    public void setSport(String sport) {
        this.sport = sport;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfLeague (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(sport);

        sb.append(")");
        return sb.toString();
    }
}
