/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfMatch implements Serializable {

    private static final long serialVersionUID = -1294511221;

    private Integer       id;
    private Integer       roundId;
    private Integer       seasonId;
    private LocalDateTime kickoffTime;
    private Integer       teamHomeId;
    private Integer       teamAwayId;
    private Integer       homeGoals;
    private Integer       awayGoals;

    public VfMatch() {}

    public VfMatch(VfMatch value) {
        this.id = value.id;
        this.roundId = value.roundId;
        this.seasonId = value.seasonId;
        this.kickoffTime = value.kickoffTime;
        this.teamHomeId = value.teamHomeId;
        this.teamAwayId = value.teamAwayId;
        this.homeGoals = value.homeGoals;
        this.awayGoals = value.awayGoals;
    }

    public VfMatch(
        Integer       id,
        Integer       roundId,
        Integer       seasonId,
        LocalDateTime kickoffTime,
        Integer       teamHomeId,
        Integer       teamAwayId,
        Integer       homeGoals,
        Integer       awayGoals
    ) {
        this.id = id;
        this.roundId = roundId;
        this.seasonId = seasonId;
        this.kickoffTime = kickoffTime;
        this.teamHomeId = teamHomeId;
        this.teamAwayId = teamAwayId;
        this.homeGoals = homeGoals;
        this.awayGoals = awayGoals;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRoundId() {
        return this.roundId;
    }

    public void setRoundId(Integer roundId) {
        this.roundId = roundId;
    }

    public Integer getSeasonId() {
        return this.seasonId;
    }

    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    public LocalDateTime getKickoffTime() {
        return this.kickoffTime;
    }

    public void setKickoffTime(LocalDateTime kickoffTime) {
        this.kickoffTime = kickoffTime;
    }

    public Integer getTeamHomeId() {
        return this.teamHomeId;
    }

    public void setTeamHomeId(Integer teamHomeId) {
        this.teamHomeId = teamHomeId;
    }

    public Integer getTeamAwayId() {
        return this.teamAwayId;
    }

    public void setTeamAwayId(Integer teamAwayId) {
        this.teamAwayId = teamAwayId;
    }

    public Integer getHomeGoals() {
        return this.homeGoals;
    }

    public void setHomeGoals(Integer homeGoals) {
        this.homeGoals = homeGoals;
    }

    public Integer getAwayGoals() {
        return this.awayGoals;
    }

    public void setAwayGoals(Integer awayGoals) {
        this.awayGoals = awayGoals;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfMatch (");

        sb.append(id);
        sb.append(", ").append(roundId);
        sb.append(", ").append(seasonId);
        sb.append(", ").append(kickoffTime);
        sb.append(", ").append(teamHomeId);
        sb.append(", ").append(teamAwayId);
        sb.append(", ").append(homeGoals);
        sb.append(", ").append(awayGoals);

        sb.append(")");
        return sb.toString();
    }
}
