/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfSport implements Serializable {

    private static final long serialVersionUID = -1807056917;

    private String  code;
    private String  name;
    private Integer halftimeDuration;
    private Integer periodDuration;

    public VfSport() {}

    public VfSport(VfSport value) {
        this.code = value.code;
        this.name = value.name;
        this.halftimeDuration = value.halftimeDuration;
        this.periodDuration = value.periodDuration;
    }

    public VfSport(
        String  code,
        String  name,
        Integer halftimeDuration,
        Integer periodDuration
    ) {
        this.code = code;
        this.name = name;
        this.halftimeDuration = halftimeDuration;
        this.periodDuration = periodDuration;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getHalftimeDuration() {
        return this.halftimeDuration;
    }

    public void setHalftimeDuration(Integer halftimeDuration) {
        this.halftimeDuration = halftimeDuration;
    }

    public Integer getPeriodDuration() {
        return this.periodDuration;
    }

    public void setPeriodDuration(Integer periodDuration) {
        this.periodDuration = periodDuration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfSport (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(halftimeDuration);
        sb.append(", ").append(periodDuration);

        sb.append(")");
        return sb.toString();
    }
}
