/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfBookmaker;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfBookmakerRecord extends UpdatableRecordImpl<VfBookmakerRecord> implements Record7<Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = -999950497;

    /**
     * Setter for <code>VF.vf_bookmaker.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.last_name</code>.
     */
    public void setLastName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>VF.vf_bookmaker.phone</code>.
     */
    public void setPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>VF.vf_bookmaker.phone</code>.
     */
    public String getPhone() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfBookmaker.VF_BOOKMAKER.ID;
    }

    @Override
    public Field<String> field2() {
        return VfBookmaker.VF_BOOKMAKER.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return VfBookmaker.VF_BOOKMAKER.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return VfBookmaker.VF_BOOKMAKER.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return VfBookmaker.VF_BOOKMAKER.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return VfBookmaker.VF_BOOKMAKER.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return VfBookmaker.VF_BOOKMAKER.PHONE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getPhone();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getPhone();
    }

    @Override
    public VfBookmakerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public VfBookmakerRecord value7(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public VfBookmakerRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfBookmakerRecord
     */
    public VfBookmakerRecord() {
        super(VfBookmaker.VF_BOOKMAKER);
    }

    /**
     * Create a detached, initialised VfBookmakerRecord
     */
    public VfBookmakerRecord(Integer id, String username, String password, String firstName, String lastName, String email, String phone) {
        super(VfBookmaker.VF_BOOKMAKER);

        set(0, id);
        set(1, username);
        set(2, password);
        set(3, firstName);
        set(4, lastName);
        set(5, email);
        set(6, phone);
    }
}
