/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfLeague;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfLeagueRecord extends UpdatableRecordImpl<VfLeagueRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -1592983635;

    /**
     * Setter for <code>VF.vf_league.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_league.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_league.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_league.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VF.vf_league.sport</code>.
     */
    public void setSport(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_league.sport</code>.
     */
    public String getSport() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfLeague.VF_LEAGUE.ID;
    }

    @Override
    public Field<String> field2() {
        return VfLeague.VF_LEAGUE.NAME;
    }

    @Override
    public Field<String> field3() {
        return VfLeague.VF_LEAGUE.SPORT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getSport();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getSport();
    }

    @Override
    public VfLeagueRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VfLeagueRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public VfLeagueRecord value3(String value) {
        setSport(value);
        return this;
    }

    @Override
    public VfLeagueRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfLeagueRecord
     */
    public VfLeagueRecord() {
        super(VfLeague.VF_LEAGUE);
    }

    /**
     * Create a detached, initialised VfLeagueRecord
     */
    public VfLeagueRecord(Integer id, String name, String sport) {
        super(VfLeague.VF_LEAGUE);

        set(0, id);
        set(1, name);
        set(2, sport);
    }
}
