/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfMatch;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfMatchRecord extends UpdatableRecordImpl<VfMatchRecord> implements Record8<Integer, Integer, Integer, LocalDateTime, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 452313606;

    /**
     * Setter for <code>VF.vf_match.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_match.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_match.round_id</code>.
     */
    public void setRoundId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_match.round_id</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VF.vf_match.season_id</code>.
     */
    public void setSeasonId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_match.season_id</code>.
     */
    public Integer getSeasonId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VF.vf_match.kickoff_time</code>.
     */
    public void setKickoffTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_match.kickoff_time</code>.
     */
    public LocalDateTime getKickoffTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>VF.vf_match.team_home_id</code>.
     */
    public void setTeamHomeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>VF.vf_match.team_home_id</code>.
     */
    public Integer getTeamHomeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>VF.vf_match.team_away_id</code>.
     */
    public void setTeamAwayId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>VF.vf_match.team_away_id</code>.
     */
    public Integer getTeamAwayId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>VF.vf_match.home_goals</code>.
     */
    public void setHomeGoals(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>VF.vf_match.home_goals</code>.
     */
    public Integer getHomeGoals() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>VF.vf_match.away_goals</code>.
     */
    public void setAwayGoals(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>VF.vf_match.away_goals</code>.
     */
    public Integer getAwayGoals() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, LocalDateTime, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, LocalDateTime, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfMatch.VF_MATCH.ID;
    }

    @Override
    public Field<Integer> field2() {
        return VfMatch.VF_MATCH.ROUND_ID;
    }

    @Override
    public Field<Integer> field3() {
        return VfMatch.VF_MATCH.SEASON_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return VfMatch.VF_MATCH.KICKOFF_TIME;
    }

    @Override
    public Field<Integer> field5() {
        return VfMatch.VF_MATCH.TEAM_HOME_ID;
    }

    @Override
    public Field<Integer> field6() {
        return VfMatch.VF_MATCH.TEAM_AWAY_ID;
    }

    @Override
    public Field<Integer> field7() {
        return VfMatch.VF_MATCH.HOME_GOALS;
    }

    @Override
    public Field<Integer> field8() {
        return VfMatch.VF_MATCH.AWAY_GOALS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getRoundId();
    }

    @Override
    public Integer component3() {
        return getSeasonId();
    }

    @Override
    public LocalDateTime component4() {
        return getKickoffTime();
    }

    @Override
    public Integer component5() {
        return getTeamHomeId();
    }

    @Override
    public Integer component6() {
        return getTeamAwayId();
    }

    @Override
    public Integer component7() {
        return getHomeGoals();
    }

    @Override
    public Integer component8() {
        return getAwayGoals();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getRoundId();
    }

    @Override
    public Integer value3() {
        return getSeasonId();
    }

    @Override
    public LocalDateTime value4() {
        return getKickoffTime();
    }

    @Override
    public Integer value5() {
        return getTeamHomeId();
    }

    @Override
    public Integer value6() {
        return getTeamAwayId();
    }

    @Override
    public Integer value7() {
        return getHomeGoals();
    }

    @Override
    public Integer value8() {
        return getAwayGoals();
    }

    @Override
    public VfMatchRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VfMatchRecord value2(Integer value) {
        setRoundId(value);
        return this;
    }

    @Override
    public VfMatchRecord value3(Integer value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public VfMatchRecord value4(LocalDateTime value) {
        setKickoffTime(value);
        return this;
    }

    @Override
    public VfMatchRecord value5(Integer value) {
        setTeamHomeId(value);
        return this;
    }

    @Override
    public VfMatchRecord value6(Integer value) {
        setTeamAwayId(value);
        return this;
    }

    @Override
    public VfMatchRecord value7(Integer value) {
        setHomeGoals(value);
        return this;
    }

    @Override
    public VfMatchRecord value8(Integer value) {
        setAwayGoals(value);
        return this;
    }

    @Override
    public VfMatchRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfMatchRecord
     */
    public VfMatchRecord() {
        super(VfMatch.VF_MATCH);
    }

    /**
     * Create a detached, initialised VfMatchRecord
     */
    public VfMatchRecord(Integer id, Integer roundId, Integer seasonId, LocalDateTime kickoffTime, Integer teamHomeId, Integer teamAwayId, Integer homeGoals, Integer awayGoals) {
        super(VfMatch.VF_MATCH);

        set(0, id);
        set(1, roundId);
        set(2, seasonId);
        set(3, kickoffTime);
        set(4, teamHomeId);
        set(5, teamAwayId);
        set(6, homeGoals);
        set(7, awayGoals);
    }
}
