/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfStandings;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfStandingsRecord extends UpdatableRecordImpl<VfStandingsRecord> implements Record5<Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1491366516;

    /**
     * Setter for <code>VF.vf_standings.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_standings.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_standings.season_id</code>.
     */
    public void setSeasonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_standings.season_id</code>.
     */
    public Integer getSeasonId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>VF.vf_standings.points</code>.
     */
    public void setPoints(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_standings.points</code>.
     */
    public Integer getPoints() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VF.vf_standings.goals_scored</code>.
     */
    public void setGoalsScored(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_standings.goals_scored</code>.
     */
    public Integer getGoalsScored() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>VF.vf_standings.goals_conceded</code>.
     */
    public void setGoalsConceded(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>VF.vf_standings.goals_conceded</code>.
     */
    public Integer getGoalsConceded() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfStandings.VF_STANDINGS.TEAM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return VfStandings.VF_STANDINGS.SEASON_ID;
    }

    @Override
    public Field<Integer> field3() {
        return VfStandings.VF_STANDINGS.POINTS;
    }

    @Override
    public Field<Integer> field4() {
        return VfStandings.VF_STANDINGS.GOALS_SCORED;
    }

    @Override
    public Field<Integer> field5() {
        return VfStandings.VF_STANDINGS.GOALS_CONCEDED;
    }

    @Override
    public Integer component1() {
        return getTeamId();
    }

    @Override
    public Integer component2() {
        return getSeasonId();
    }

    @Override
    public Integer component3() {
        return getPoints();
    }

    @Override
    public Integer component4() {
        return getGoalsScored();
    }

    @Override
    public Integer component5() {
        return getGoalsConceded();
    }

    @Override
    public Integer value1() {
        return getTeamId();
    }

    @Override
    public Integer value2() {
        return getSeasonId();
    }

    @Override
    public Integer value3() {
        return getPoints();
    }

    @Override
    public Integer value4() {
        return getGoalsScored();
    }

    @Override
    public Integer value5() {
        return getGoalsConceded();
    }

    @Override
    public VfStandingsRecord value1(Integer value) {
        setTeamId(value);
        return this;
    }

    @Override
    public VfStandingsRecord value2(Integer value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public VfStandingsRecord value3(Integer value) {
        setPoints(value);
        return this;
    }

    @Override
    public VfStandingsRecord value4(Integer value) {
        setGoalsScored(value);
        return this;
    }

    @Override
    public VfStandingsRecord value5(Integer value) {
        setGoalsConceded(value);
        return this;
    }

    @Override
    public VfStandingsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfStandingsRecord
     */
    public VfStandingsRecord() {
        super(VfStandings.VF_STANDINGS);
    }

    /**
     * Create a detached, initialised VfStandingsRecord
     */
    public VfStandingsRecord(Integer teamId, Integer seasonId, Integer points, Integer goalsScored, Integer goalsConceded) {
        super(VfStandings.VF_STANDINGS);

        set(0, teamId);
        set(1, seasonId);
        set(2, points);
        set(3, goalsScored);
        set(4, goalsConceded);
    }
}
