/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.records;


import dualsoft.vf.jooq.model.tables.VfTeam;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfTeamRecord extends UpdatableRecordImpl<VfTeamRecord> implements Record7<Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 10864345;

    /**
     * Setter for <code>VF.vf_team.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>VF.vf_team.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>VF.vf_team.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>VF.vf_team.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>VF.vf_team.league_id</code>.
     */
    public void setLeagueId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>VF.vf_team.league_id</code>.
     */
    public Integer getLeagueId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>VF.vf_team.attack_home</code>.
     */
    public void setAttackHome(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>VF.vf_team.attack_home</code>.
     */
    public BigDecimal getAttackHome() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>VF.vf_team.attack_away</code>.
     */
    public void setAttackAway(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>VF.vf_team.attack_away</code>.
     */
    public BigDecimal getAttackAway() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>VF.vf_team.defense_home</code>.
     */
    public void setDefenseHome(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>VF.vf_team.defense_home</code>.
     */
    public BigDecimal getDefenseHome() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>VF.vf_team.defense_away</code>.
     */
    public void setDefenseAway(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>VF.vf_team.defense_away</code>.
     */
    public BigDecimal getDefenseAway() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VfTeam.VF_TEAM.ID;
    }

    @Override
    public Field<String> field2() {
        return VfTeam.VF_TEAM.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return VfTeam.VF_TEAM.LEAGUE_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return VfTeam.VF_TEAM.ATTACK_HOME;
    }

    @Override
    public Field<BigDecimal> field5() {
        return VfTeam.VF_TEAM.ATTACK_AWAY;
    }

    @Override
    public Field<BigDecimal> field6() {
        return VfTeam.VF_TEAM.DEFENSE_HOME;
    }

    @Override
    public Field<BigDecimal> field7() {
        return VfTeam.VF_TEAM.DEFENSE_AWAY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getLeagueId();
    }

    @Override
    public BigDecimal component4() {
        return getAttackHome();
    }

    @Override
    public BigDecimal component5() {
        return getAttackAway();
    }

    @Override
    public BigDecimal component6() {
        return getDefenseHome();
    }

    @Override
    public BigDecimal component7() {
        return getDefenseAway();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getLeagueId();
    }

    @Override
    public BigDecimal value4() {
        return getAttackHome();
    }

    @Override
    public BigDecimal value5() {
        return getAttackAway();
    }

    @Override
    public BigDecimal value6() {
        return getDefenseHome();
    }

    @Override
    public BigDecimal value7() {
        return getDefenseAway();
    }

    @Override
    public VfTeamRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VfTeamRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public VfTeamRecord value3(Integer value) {
        setLeagueId(value);
        return this;
    }

    @Override
    public VfTeamRecord value4(BigDecimal value) {
        setAttackHome(value);
        return this;
    }

    @Override
    public VfTeamRecord value5(BigDecimal value) {
        setAttackAway(value);
        return this;
    }

    @Override
    public VfTeamRecord value6(BigDecimal value) {
        setDefenseHome(value);
        return this;
    }

    @Override
    public VfTeamRecord value7(BigDecimal value) {
        setDefenseAway(value);
        return this;
    }

    @Override
    public VfTeamRecord values(Integer value1, String value2, Integer value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VfTeamRecord
     */
    public VfTeamRecord() {
        super(VfTeam.VF_TEAM);
    }

    /**
     * Create a detached, initialised VfTeamRecord
     */
    public VfTeamRecord(Integer id, String name, Integer leagueId, BigDecimal attackHome, BigDecimal attackAway, BigDecimal defenseHome, BigDecimal defenseAway) {
        super(VfTeam.VF_TEAM);

        set(0, id);
        set(1, name);
        set(2, leagueId);
        set(3, attackHome);
        set(4, attackAway);
        set(5, defenseHome);
        set(6, defenseAway);
    }
}
