/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model;


import dualsoft.vf.jooq.model.tables.VfBookmaker;
import dualsoft.vf.jooq.model.tables.VfLeague;
import dualsoft.vf.jooq.model.tables.VfMatch;
import dualsoft.vf.jooq.model.tables.VfOdds;
import dualsoft.vf.jooq.model.tables.VfOperator;
import dualsoft.vf.jooq.model.tables.VfRound;
import dualsoft.vf.jooq.model.tables.VfSeason;
import dualsoft.vf.jooq.model.tables.VfSport;
import dualsoft.vf.jooq.model.tables.VfStandings;
import dualsoft.vf.jooq.model.tables.VfTeam;


/**
 * Convenience access to all tables in VF
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>VF.vf_bookmaker</code>.
     */
    public static final VfBookmaker VF_BOOKMAKER = VfBookmaker.VF_BOOKMAKER;

    /**
     * The table <code>VF.vf_league</code>.
     */
    public static final VfLeague VF_LEAGUE = VfLeague.VF_LEAGUE;

    /**
     * The table <code>VF.vf_match</code>.
     */
    public static final VfMatch VF_MATCH = VfMatch.VF_MATCH;

    /**
     * The table <code>VF.vf_odds</code>.
     */
    public static final VfOdds VF_ODDS = VfOdds.VF_ODDS;

    /**
     * The table <code>VF.vf_operator</code>.
     */
    public static final VfOperator VF_OPERATOR = VfOperator.VF_OPERATOR;

    /**
     * The table <code>VF.vf_round</code>.
     */
    public static final VfRound VF_ROUND = VfRound.VF_ROUND;

    /**
     * The table <code>VF.vf_season</code>.
     */
    public static final VfSeason VF_SEASON = VfSeason.VF_SEASON;

    /**
     * The table <code>VF.vf_sport</code>.
     */
    public static final VfSport VF_SPORT = VfSport.VF_SPORT;

    /**
     * The table <code>VF.vf_standings</code>.
     */
    public static final VfStandings VF_STANDINGS = VfStandings.VF_STANDINGS;

    /**
     * The table <code>VF.vf_team</code>.
     */
    public static final VfTeam VF_TEAM = VfTeam.VF_TEAM;
}
