/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model;


import dualsoft.vf.jooq.model.tables.VfBookmaker;
import dualsoft.vf.jooq.model.tables.VfLeague;
import dualsoft.vf.jooq.model.tables.VfMatch;
import dualsoft.vf.jooq.model.tables.VfOdds;
import dualsoft.vf.jooq.model.tables.VfOperator;
import dualsoft.vf.jooq.model.tables.VfRound;
import dualsoft.vf.jooq.model.tables.VfSeason;
import dualsoft.vf.jooq.model.tables.VfSport;
import dualsoft.vf.jooq.model.tables.VfStandings;
import dualsoft.vf.jooq.model.tables.VfTeam;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vf extends SchemaImpl {

    private static final long serialVersionUID = -1860525011;

    /**
     * The reference instance of <code>VF</code>
     */
    public static final Vf VF = new Vf();

    /**
     * The table <code>VF.vf_bookmaker</code>.
     */
    public final VfBookmaker VF_BOOKMAKER = VfBookmaker.VF_BOOKMAKER;

    /**
     * The table <code>VF.vf_league</code>.
     */
    public final VfLeague VF_LEAGUE = VfLeague.VF_LEAGUE;

    /**
     * The table <code>VF.vf_match</code>.
     */
    public final VfMatch VF_MATCH = VfMatch.VF_MATCH;

    /**
     * The table <code>VF.vf_odds</code>.
     */
    public final VfOdds VF_ODDS = VfOdds.VF_ODDS;

    /**
     * The table <code>VF.vf_operator</code>.
     */
    public final VfOperator VF_OPERATOR = VfOperator.VF_OPERATOR;

    /**
     * The table <code>VF.vf_round</code>.
     */
    public final VfRound VF_ROUND = VfRound.VF_ROUND;

    /**
     * The table <code>VF.vf_season</code>.
     */
    public final VfSeason VF_SEASON = VfSeason.VF_SEASON;

    /**
     * The table <code>VF.vf_sport</code>.
     */
    public final VfSport VF_SPORT = VfSport.VF_SPORT;

    /**
     * The table <code>VF.vf_standings</code>.
     */
    public final VfStandings VF_STANDINGS = VfStandings.VF_STANDINGS;

    /**
     * The table <code>VF.vf_team</code>.
     */
    public final VfTeam VF_TEAM = VfTeam.VF_TEAM;

    /**
     * No further instances allowed
     */
    private Vf() {
        super("VF", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.VF_BOOKMAKER_ID_SEQ,
            Sequences.VF_LEAGUE_ID_SEQ,
            Sequences.VF_MATCH_ID_SEQ,
            Sequences.VF_ODDS_ID_SEQ,
            Sequences.VF_SEASON_ID_SEQ,
            Sequences.VF_TEAM_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            VfBookmaker.VF_BOOKMAKER,
            VfLeague.VF_LEAGUE,
            VfMatch.VF_MATCH,
            VfOdds.VF_ODDS,
            VfOperator.VF_OPERATOR,
            VfRound.VF_ROUND,
            VfSeason.VF_SEASON,
            VfSport.VF_SPORT,
            VfStandings.VF_STANDINGS,
            VfTeam.VF_TEAM);
    }
}
