/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfOperator implements Serializable {

    private static final long serialVersionUID = -1146976085;

    private String code;
    private String name;
    private String username;
    private String password;
    private String email;
    private String phone;

    public VfOperator() {}

    public VfOperator(VfOperator value) {
        this.code = value.code;
        this.name = value.name;
        this.username = value.username;
        this.password = value.password;
        this.email = value.email;
        this.phone = value.phone;
    }

    public VfOperator(
        String code,
        String name,
        String username,
        String password,
        String email,
        String phone
    ) {
        this.code = code;
        this.name = name;
        this.username = username;
        this.password = password;
        this.email = email;
        this.phone = phone;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfOperator (");

        sb.append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
