/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfRound implements Serializable {

    private static final long serialVersionUID = 657387761;

    private Integer roundNumber;
    private Integer seasonId;

    public VfRound() {}

    public VfRound(VfRound value) {
        this.roundNumber = value.roundNumber;
        this.seasonId = value.seasonId;
    }

    public VfRound(
        Integer roundNumber,
        Integer seasonId
    ) {
        this.roundNumber = roundNumber;
        this.seasonId = seasonId;
    }

    public Integer getRoundNumber() {
        return this.roundNumber;
    }

    public void setRoundNumber(Integer roundNumber) {
        this.roundNumber = roundNumber;
    }

    public Integer getSeasonId() {
        return this.seasonId;
    }

    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfRound (");

        sb.append(roundNumber);
        sb.append(", ").append(seasonId);

        sb.append(")");
        return sb.toString();
    }
}
