/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfStandings implements Serializable {

    private static final long serialVersionUID = 1591270156;

    private Integer teamId;
    private Integer seasonId;
    private Integer points;
    private Integer goalsScored;
    private Integer goalsConceded;

    public VfStandings() {}

    public VfStandings(VfStandings value) {
        this.teamId = value.teamId;
        this.seasonId = value.seasonId;
        this.points = value.points;
        this.goalsScored = value.goalsScored;
        this.goalsConceded = value.goalsConceded;
    }

    public VfStandings(
        Integer teamId,
        Integer seasonId,
        Integer points,
        Integer goalsScored,
        Integer goalsConceded
    ) {
        this.teamId = teamId;
        this.seasonId = seasonId;
        this.points = points;
        this.goalsScored = goalsScored;
        this.goalsConceded = goalsConceded;
    }

    public Integer getTeamId() {
        return this.teamId;
    }

    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    public Integer getSeasonId() {
        return this.seasonId;
    }

    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    public Integer getPoints() {
        return this.points;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    public Integer getGoalsScored() {
        return this.goalsScored;
    }

    public void setGoalsScored(Integer goalsScored) {
        this.goalsScored = goalsScored;
    }

    public Integer getGoalsConceded() {
        return this.goalsConceded;
    }

    public void setGoalsConceded(Integer goalsConceded) {
        this.goalsConceded = goalsConceded;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfStandings (");

        sb.append(teamId);
        sb.append(", ").append(seasonId);
        sb.append(", ").append(points);
        sb.append(", ").append(goalsScored);
        sb.append(", ").append(goalsConceded);

        sb.append(")");
        return sb.toString();
    }
}
