/*
 * This file is generated by jOOQ.
 */
package dualsoft.vf.jooq.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VfTeam implements Serializable {

    private static final long serialVersionUID = 978335427;

    private Integer    id;
    private String     name;
    private Integer    leagueId;
    private BigDecimal attackHome;
    private BigDecimal attackAway;
    private BigDecimal defenseHome;
    private BigDecimal defenseAway;

    public VfTeam() {}

    public VfTeam(VfTeam value) {
        this.id = value.id;
        this.name = value.name;
        this.leagueId = value.leagueId;
        this.attackHome = value.attackHome;
        this.attackAway = value.attackAway;
        this.defenseHome = value.defenseHome;
        this.defenseAway = value.defenseAway;
    }

    public VfTeam(
        Integer    id,
        String     name,
        Integer    leagueId,
        BigDecimal attackHome,
        BigDecimal attackAway,
        BigDecimal defenseHome,
        BigDecimal defenseAway
    ) {
        this.id = id;
        this.name = name;
        this.leagueId = leagueId;
        this.attackHome = attackHome;
        this.attackAway = attackAway;
        this.defenseHome = defenseHome;
        this.defenseAway = defenseAway;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getLeagueId() {
        return this.leagueId;
    }

    public void setLeagueId(Integer leagueId) {
        this.leagueId = leagueId;
    }

    public BigDecimal getAttackHome() {
        return this.attackHome;
    }

    public void setAttackHome(BigDecimal attackHome) {
        this.attackHome = attackHome;
    }

    public BigDecimal getAttackAway() {
        return this.attackAway;
    }

    public void setAttackAway(BigDecimal attackAway) {
        this.attackAway = attackAway;
    }

    public BigDecimal getDefenseHome() {
        return this.defenseHome;
    }

    public void setDefenseHome(BigDecimal defenseHome) {
        this.defenseHome = defenseHome;
    }

    public BigDecimal getDefenseAway() {
        return this.defenseAway;
    }

    public void setDefenseAway(BigDecimal defenseAway) {
        this.defenseAway = defenseAway;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VfTeam (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(leagueId);
        sb.append(", ").append(attackHome);
        sb.append(", ").append(attackAway);
        sb.append(", ").append(defenseHome);
        sb.append(", ").append(defenseAway);

        sb.append(")");
        return sb.toString();
    }
}
